repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # - id: trailing-whitespace  # handled by ruff-format
      # - id: end-of-file-fixer  # handled by ruff-format
      - id: check-yaml
#      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.5
    hooks:
      # Only run isort for for now, --select I == isort
      - id: ruff
        args: [ --fix, --select, I]
      # Run the formatter.
      - id: ruff-format
